### ISSUE TITLE
500 internal server error on login

### ISSUE THREAD

**Issue by ionphractal** [cloudfoundry-community/bui#3]
Hi!
I tried deploying bui with https://github.com/cloudfoundry-community/bui-boshrelease but I can't log into the ui (not with default password admin/admin nor with director password). It uses the latest release 0.2.2.

The following error pops up in the log (or stdout if running the binary on the dev machine) once I hit "Login":
`2017/03/08 16:56:43 Error unmarshalling info invalid character '<' looking for beginning of value`

The browser redirects me to "http://localhost:9304/#/login?error=unauthorized" but it sais 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
in the developer console (which shouldn't be the normal "password wrong" reply) I guess.

config.yml:
```
listen_addr: localhost:9304
web_root: ui
cookie_secret: super-secret
bosh_addr: https://172.16.1.11:25555
skip_ssl_validation: true
uaa:
  client_id:
  client_secret:
```

```
bui-linux-amd64$ ls -lah
insgesamt 9,7M
drwxr-xr-x 3 ubuntu ubuntu 4,0K Mär  8 16:56 .
drwxrwxr-x 3 ubuntu ubuntu 4,0K Mär  8 17:00 ..
-rwxr-xr-x 1 ubuntu ubuntu 9,7M Jan  5 16:20 bui
-rw-rw-r-- 1 ubuntu ubuntu  168 Mär  8 16:56 config.yml
drwxr-xr-x 7 ubuntu ubuntu 4,0K Jan  5 16:17 ui
bui-linux-amd64$ ./bui --version
bui v0.2.2
```

Is this related to the yaml parsing error that should've been addressed in https://github.com/cloudfoundry-community/bui/commit/b37d07aec23b4703c45f0e140efae7564366709f ?
Or am I doing something wrong?
